name: Check Page Workflow

on:
  schedule:
    - cron: '5 */4 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Logging Level'
        required: true
        default: 'DEBUG'

jobs:
  check-page:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create env file from secret
      run: echo "${{ secrets.ENV_FILE }}" > .env
    
    - name: Append LOG_LEVEL to .env
      if: github.event_name == 'workflow_dispatch'
      run: echo "LOG_LEVEL=${{ github.event.inputs.logLevel }}" >> .env

    - name: Docker Compose run
      run: docker compose up app

    - name: Check Docker Log
      run: docker compose logs app
