name: Check Page Workflow

on:
  schedule:
    - cron: '5 */4 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Logging Level'
        required: true
        default: 'DEBUG'
        type: choice
        options:
          - DEBUG
          - INFO
          - WARNING

env:
  REMOTE_IMAGE_NAME: ${{ vars.REMOTE_IMAGE_NAME }}
  IMAGE_NAME: utahiro-calendar
  EVENT_LOG: event.log

jobs:
  check-page:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Define variables
      run: |
        echo "USER_AGENT=$USER_AGENT"   >> .env
        echo "EVENT_TITLE=$EVENT_TITLE" >> .env
        echo "CALENDAR_ID=$CALENDAR_ID" >> .env
        echo "PAGE_URL=$PAGE_URL"       >> .env
        echo "$USER_TOKEN" >> token.json
      env:
        USER_AGENT: ${{ vars.USER_AGENT }}
        EVENT_TITLE: ${{ vars.EVENT_TITLE }}
        CALENDAR_ID: ${{ vars.CALENDAR_ID }}
        PAGE_URL: ${{ secrets.PAGE_URL }}
        USER_TOKEN: ${{ secrets.USER_TOKEN }}

    - name: Append LOG_LEVEL to .env
      if: github.event_name == 'workflow_dispatch'
      run: echo "LOG_LEVEL=${{ github.event.inputs.logLevel }}" >> .env

    - name: Login to ghrc.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull image
      run: |
        docker pull "$REMOTE_IMAGE_NAME"
        docker tag "$REMOTE_IMAGE_NAME" "$IMAGE_NAME"

    - name: Check event
      run: docker compose run app

    - name: Commit and push event log
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'
        git add -N "$EVENT_LOG"
        git diff --cached --exit-code --quiet || git commit -m "Found new event"
        git push
