name: Check Page Workflow

on:
  schedule:
    - cron: '5 */4 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Logging Level'
        required: true
        default: 'DEBUG'

env:
  PATH_CACHE: /tmp/docker-image-arc.tar
  LOCAL_IMAGE_NAME: playwright-requests

jobs:
  check-page:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create env file from secret
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "PAGE_URL=${{ secrets.PAGE_URL }}" >> .env
        echo "EVENT_TITLE=${{ vars.EVENT_TITLE }}" >> .env
        echo "SERVER_URL=${{ vars.SERVER_URL }}" >> .env
        echo "USER_AGENT=${{ vars.USER_AGENT }}" >> .env
    
    - name: Append LOG_LEVEL to .env
      if: github.event_name == 'workflow_dispatch'
      run: echo "LOG_LEVEL=${{ github.event.inputs.logLevel }}" >> .env
    
    # - name: Check Cache Image Archive
    #   uses: actions/cache@v3
    #   id: cache
    #   with:
    #     path: ${{ env.PATH_CACHE }}}
    #     key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}
    
    # - name: Load Cache Image Archive
    #   if: steps.cache.outputs.cache-hit == 'true'
    #   run: docker load -i ${{ env.PATH_CACHE }}}
    
    # - name: Build Image and Save Image Archive
    #   if: steps.cache.outputs.cache-hit != 'true'
    #   run: |
    #     docker build . -t ${{ env.LOCAL_IMAGE_NAME }}
    #     docker save ${{ env.LOCAL_IMAGE_NAME }} -o ${{ env.PATH_CACHE }}}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker Pull
      run: |
        docker pull ${{ vars.REMOTE_IMAGE_NAME }}
        docker tag ${{ vars.REMOTE_IMAGE_NAME }} ${{ env.LOCAL_IMAGE_NAME }}
    
    - name: Docker Compose run
      run: docker compose up app

    - name: Check Docker Log
      run: docker compose logs app
