name: Check Page Workflow

on:
  push:
  workflow_dispatch:

jobs:
  check-page:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: |
          pip install -r requirements.txt
          playwright install

      - run: python3 app/main.py
        env:
          CALENDAR_ID: ${{ vars.CALENDAR_ID }}
          PAGE_URL: ${{ secrets.PAGE_URL }}
