name: Check Page Workflow

on:
  schedule:
    - cron: '5 */4 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Logging Level'
        required: true
        default: 'DEBUG'

env:
  PATH_CACHE: /tmp/docker-image-arc.tar

jobs:
  check-page:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create env file from secret
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "PAGE_URL=${{ secrets.PAGE_URL }}" >> .env
        echo "EVENT_TITLE=${{ vars.EVENT_TITLE }}" >> .env
        echo "SERVER_URL=${{ vars.SERVER_URL }}" >> .env
        echo "USER_AGENT=${{ vars.USER_AGENT }}" >> .env
    
    - name: Append LOG_LEVEL to .env
      if: github.event_name == 'workflow_dispatch'
      run: echo "LOG_LEVEL=${{ github.event.inputs.logLevel }}" >> .env
    
    - name: Check Cache Image
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ env.PATH_CACHE }}}
        key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}
    
    - name: Load Cache Image
      if: steps.cache.cache-hit == 'true'
      run: docker load -i ${{ env.PATH_CACHE }}}
    
    - name: Build Image
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        docker build . -t playwright-requests
        docker save playwright-requests -o ${{ env.PATH_CACHE }}}
    
    - name: Docker Compose run
      run: docker compose up app

    - name: Check Docker Log
      run: docker compose logs app
