name: Check Page Workflow

on:
  push:
  workflow_dispatch:

env:
  REMOTE_IMAGE_NAME: ${{ vars.REMOTE_IMAGE_NAME }}
  IMAGE_NAME: utahiro-calendar
  EVENT_LOG: event.log

jobs:
  check-page:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define variables
        run: |
          cat << EOF > .env
          CALENDAR_ID="$CALENDAR_ID"
          PAGE_URL="$PAGE_URL"
          EOF
        env:
          CALENDAR_ID: ${{ vars.CALENDAR_ID }}
          PAGE_URL: ${{ secrets.PAGE_URL }}

      - run: docker compose pull app
      - id: run_app
        continue-on-error: true
        run: docker compose run app

      - name: Upload Artifact
        if: ${{ steps.run_app.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
