name: Test Workflow

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "utahiro-calendar"
          service_account: google-calendar-api@utahiro-calendar.iam.gserviceaccount.com
          workload_identity_provider: "projects/306157530435/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          token_format: "access_token"
          access_token_scopes: "https://www.googleapis.com/auth/calendar"
          create_credentials_file: true
    
      - run: pip install -r requirements.txt && pytest -v
